import { v4 as uuidv4 } from 'uuid';

const rawData = [
  {
    name: `Zora Helm`,
    category: 'armor',
    type: 'armorHead',
    value: 3,
    description: `Zora headgear made from dragon scales. Increases swimming speed and allows you to use Spin Attack.`,
    bonus: 'swimming',
    isEquipped: false,
    image: `/src/img/armors/BotW_Zora_Helm_Icon.png`,
  },
  {
    name: `Zora Armor`,
    category: 'armor',
    type: 'armorChest',
    value: 3,
    description: `Custom armor painstakingly crafted by each generation's Zora princess for her future husband. Wearing it will give you the ability to swim up waterfalls.`,
    bonus: 'swimming',
    isEquipped: false,
    image: `/src/img/armors/BotW_Zora_Armor_Icon.png`,
  },
  {
    name: `Zora Greaves`,
    category: 'armor',
    type: 'armorBottom',
    value: 3,
    description: `These greave have been passed down among the Zora for generations. It's been said they're crafted using dragon scales. Equip them to swim faster.`,
    bonus: 'swimming',
    isEquipped: false,
    image: `/src/img/armors/BotW_Zora_Greaves_Icon.png`,
  },
  {
    name: `Climber's Bandanna`,
    category: 'armor',
    type: 'armorHead',
    value: 3,
    description: `It may look like a regular bandanna, but it's actually infused with ancient technology that enhances core strength to improve your climbing ability.`,
    bonus: 'climbing',
    isEquipped: false,
    image: `/src/img/armors/BotW_Climber's_Bandanna_Icon.png`,
  },
  {
    name: `Climbing Gear`,
    category: 'armor',
    type: 'armorChest',
    value: 3,
    description: `The ancient technology in this gear will make you a better climber. The special no-slip gloves help you use your energy more efficiently to facilitate nimble climbing.`,
    bonus: 'climbing',
    isEquipped: false,
    image: `/src/img/armors/BotW_Climbing_Gear_Icon.png`,
  },
  {
    name: `Climbing Boots`,
    category: 'armor',
    type: 'armorBottom',
    value: 3,
    description: `These rock-climbing boots have special no-slip toes that help you cling to walls. This ancient technology facilitates more nimble climbing.`,
    bonus: 'climbing',
    isEquipped: false,
    image: `/src/img/armors/BotW_Climbing_Boots_Icon.png`,
  },
  {
    name: `Flamebreaker Helm`,
    category: 'armor',
    type: 'armorHead',
    value: 3,
    description: `Stone headgear made by Goron craftsmen to protect tourists visiting Goron City. As if its flame resistance isn't enough of a selling point, it also covers your entire head!`,
    bonus: 'resistFire',
    isEquipped: false,
    image: `/src/img/armors/BotW_Flamebreaker_Helm_Icon.png`,
  },
  {
    name: `Flamebreaker Armor`,
    category: 'armor',
    type: 'armorChest',
    value: 3,
    description: `Armor crafted by Gorons for Hylians curious enough to visit Goron City. It's made from fire-resistant rocks to protect the wearer.`,
    bonus: 'resistFire',
    isEquipped: false,
    image: `/src/img/armors/BotW_Flamebreaker_Armor_Icon.png`,
  },
  {
    name: `Flamebreaker Boots`,
    category: 'armor',
    type: 'armorBottom',
    value: 3,
    description: `Goron artisans used flame-resistant rocks to craft these fireproof boots for curious Hylians visiting Goron City.`,
    bonus: 'resistFire',
    isEquipped: false,
    image: `/src/img/armors/BotW_Flamebreaker_Boots_Icon.png`,
  },
  {
    name: `Cap of the Hero`,
    category: 'armor',
    type: 'armorHead',
    value: 3,
    description: `According to legend, this cap was once treasured by an ancient hero. It's quite the simple cap, yet there's something about it that's just so appealing...`,
    bonus: null,
    isEquipped: false,
    image: '/src/img/armors/BotW_Cap_of_the_Hero_Icon.png',
  },
  {
    name: `Champion's Tunic`,
    category: 'armor',
    type: 'armorChest',
    value: 5,
    description: `In ancient Hyrule, this garment could only be worn by one who had earned the respect of the royal family. Equipping it will reveal an enemy's life gauge.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/armors/BotW_Champion's_Tunic_Icon.png`,
  },
  {
    name: `Hylian Trousers`,
    category: 'armor',
    type: 'armorBottom',
    value: 3,
    description: `Traditional dress trousers of Hyrule. The plush fabric makes these trousers quite comfortable, and their high durability makes them ideal for travelers.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/armors/BotW_Hylian_Trousers_Icon.png`,
  },
  {
    name: `Wooden Shield`,
    category: 'shield',
    type: 'shield',
    value: 2,
    description: `This lightweight, simple shield is ideal for less-experienced fighters. It can withstand light attacks, but blocking stronger blows is not recommended.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/shields/BotW_Wooden_Shield_Icon.png`,
  },
  {
    name: `BotW Traveler's Shield`,
    category: 'shield',
    type: 'shield',
    value: 4,
    description: `A sturdy shield loved by many an adventurer. It is made of animal hide and sturdy wood and is best suited to defending against weak monsters or animals.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/shields/BotW_Traveler's_Shield_Icon.png`,
  },
  {
    name: `BotW Gerudo Shield`,
    category: 'shield',
    type: 'shield',
    value: 20,
    description: `The design of this metal shield has changed over time to match the Gerudo's sword-and-shield fighting style. It's favored by soldiers and travelers alike.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/shields/BotW_Gerudo_Shield_Icon.png`,
  },
  {
    name: `BotW Ancient Shield`,
    category: 'shield',
    type: 'shield',
    value: 70,
    description: `This shield was made using ancient Sheikah technology. Its surface glows blue when raised in defense. Enhanced functionality allows it to deflect Guardian beams.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/shields/BotW_Ancient_Shield_Icon.png`,
  },
  {
    name: `Tree Branch`,
    category: 'weapon',
    type: 'weapon',
    value: 2,
    description: `Wooden branches such as this are pretty common, but it's surprisingly well-balanced. It doesn't do much damage but can serve as a weapon in a pinch.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Tree_Branch_Icon.png`,
  },
  {
    name: `Ancient Short Sword`,
    category: 'weapon',
    type: 'weapon',
    value: 40,
    description: `The blade of this sword was made using an ancient power lost to this modern age. Its blade appears only when drawn, and its cutting power surpasses metal swords.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Ancient_Short_Sword_Icon.png`,
  },
  {
    name: `Dragonbone Boko Club`,
    category: 'weapon',
    type: 'weapon',
    value: 24,
    description: `This Bokoblin club has been reinforced with fossilized bones to maximize clobbering potential. Only the brawniest of Bokoblins can manage its immense weight.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Dragonbone_Boko_Club_Icon.png`,
  },
  {
    name: `Feathered Edge`,
    category: 'weapon',
    type: 'weapon',
    value: 15,
    description: `Rito craftsmen forged this lightweight, double-edge sword so Rito warriors could soar into battle unhindered by its weight.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Feathered_Edge_Icon.png`,
  },
  {
    name: `Flameblade`,
    category: 'weapon',
    type: 'weapon',
    value: 24,
    description: `This magical sword was forged in the lava of Death Mountain. It leaves white-hot flames in its wake when the blade glows red.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Flameblade_Icon.png`,
  },
  {
    name: `Soldier's Broadsword`,
    category: 'weapon',
    type: 'weapon',
    value: 14,
    description: `A sword brandished by the soldiers who once protected Hyrule Castle. Its durable blade is well tuned for slaying monsters.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Soldier's_Broadsword_Icon.png`,
  },
  {
    name: `Royal Claymore`,
    category: 'weapon',
    type: 'weapon',
    value: 52,
    description: `A two-handed sword issued to the Hyrulean royal family's immediate guard detail. Its powerful strikes are said to crush an opponent's body and resolve alike.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Royal_Claymore_Icon.png`,
  },
  {
    name: `Master Sword`,
    category: 'weapon',
    type: 'weapon',
    value: 30,
    description: `The Legendary sword that seals the darkness. Its blade gleams with a sacred luster that can oppose the Calamity. Only a hero chosen by the sword itself may wield it.`,
    bonus: null,
    isEquipped: false,
    image: `/src/img/weapons/BotW_Master_Sword_Icon.png`,
  },
];

const itemsData = rawData.reduce(
  (acc, item) => {
    const itemId = uuidv4();

    return {
      byId: {
        ...acc.byId,
        [itemId]: { ...item, id: itemId },
      },
      allIds: [...acc.allIds, itemId],
    };
  },
  { byId: {}, allIds: [] }
);

export default itemsData;
